import { InventoryItem } from '../types';

export const INITIAL_INVENTORY_CATALOG: InventoryItem[] = [
  // --- ALUMINUM PROFILES (BATANG 6 METER) ---
  {
    id: 'mat-alex-4in-wh',
    itemCode: 'ALX-4IN-WH',
    name: 'Kusen Alumunium Alexindo 4 Inch White',
    category: 'aluminum',
    brand: 'Alexindo',
    color: 'White (Putih)',
    spec: '4 Inch',
    unit: 'batang',
    pricePerUnit: 185000, // Rp 185.000 / Batang 6m
    stockQuantity: 24,
    minStockThreshold: 10,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-alex-4in-bk',
    itemCode: 'ALX-4IN-BK',
    name: 'Kusen Alumunium Alexindo 4 Inch Black',
    category: 'aluminum',
    brand: 'Alexindo',
    color: 'Black (Hitam)',
    spec: '4 Inch',
    unit: 'batang',
    pricePerUnit: 185000,
    stockQuantity: 18,
    minStockThreshold: 8,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-alex-4in-slv',
    itemCode: 'ALX-4IN-SLV',
    name: 'Kusen Alumunium Alexindo 4 Inch Anodized Silver',
    category: 'aluminum',
    brand: 'Alexindo',
    color: 'Anodized Silver',
    spec: '4 Inch',
    unit: 'batang',
    pricePerUnit: 165000,
    stockQuantity: 30,
    minStockThreshold: 10,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-alex-3in-wh',
    itemCode: 'ALX-3IN-WH',
    name: 'Kusen Alumunium Alexindo 3 Inch White',
    category: 'aluminum',
    brand: 'Alexindo',
    color: 'White (Putih)',
    spec: '3 Inch',
    unit: 'batang',
    pricePerUnit: 155000,
    stockQuantity: 12,
    minStockThreshold: 5,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-ykk-4in-wh',
    itemCode: 'YKK-4IN-WH',
    name: 'Kusen Alumunium YKK AP 4 Inch White',
    category: 'aluminum',
    brand: 'YKK AP',
    color: 'White (Putih)',
    spec: '4 Inch',
    unit: 'batang',
    pricePerUnit: 295000, // Premium Brand YKK
    stockQuantity: 8,
    minStockThreshold: 6,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-ykk-4in-bk',
    itemCode: 'YKK-4IN-BK',
    name: 'Kusen Alumunium YKK AP 4 Inch Black Anodized',
    category: 'aluminum',
    brand: 'YKK AP',
    color: 'Black (Hitam)',
    spec: '4 Inch',
    unit: 'batang',
    pricePerUnit: 310000,
    stockQuantity: 5,
    minStockThreshold: 6, // LOW STOCK TRIGGER ALERT DEMO
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-forta-4in-wh',
    itemCode: 'FRT-4IN-WH',
    name: 'Kusen Alumunium Forta 4 Inch White',
    category: 'aluminum',
    brand: 'Forta',
    color: 'White (Putih)',
    spec: '4 Inch',
    unit: 'batang',
    pricePerUnit: 145000,
    stockQuantity: 40,
    minStockThreshold: 12,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-dacon-4in-wd',
    itemCode: 'DCN-4IN-WD',
    name: 'Kusen Alumunium Dacon 4 Inch Urat Kayu (Wood)',
    category: 'aluminum',
    brand: 'Dacon',
    color: 'Urat Kayu (Wood)',
    spec: '4 Inch',
    unit: 'batang',
    pricePerUnit: 235000,
    stockQuantity: 3, // LOW STOCK ALERT
    minStockThreshold: 5,
    lastUpdated: new Date().toISOString(),
  },

  // --- GLASS TYPES (PER METER PERSEGI / M2) ---
  {
    id: 'mat-glass-polos-5mm',
    itemCode: 'GLS-PLS-5',
    name: 'Kaca Polos / Bening 5mm',
    category: 'glass',
    spec: '5mm',
    unit: 'm2',
    pricePerUnit: 125000, // Rp 125.000 / m2
    stockQuantity: 50,
    minStockThreshold: 15,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-glass-rayban-5mm',
    itemCode: 'GLS-RYB-5',
    name: 'Kaca Rayban / Gelap 5mm',
    category: 'glass',
    spec: '5mm',
    unit: 'm2',
    pricePerUnit: 145000,
    stockQuantity: 35,
    minStockThreshold: 10,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-glass-frosted-5mm',
    itemCode: 'GLS-FST-5',
    name: 'Kaca Es / Frosted / Buram 5mm',
    category: 'glass',
    spec: '5mm',
    unit: 'm2',
    pricePerUnit: 160000,
    stockQuantity: 20,
    minStockThreshold: 8,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-glass-tempered-8mm',
    itemCode: 'GLS-TMP-8',
    name: 'Kaca Tempered Safety 8mm',
    category: 'glass',
    spec: '8mm',
    unit: 'm2',
    pricePerUnit: 380000,
    stockQuantity: 10,
    minStockThreshold: 5,
    lastUpdated: new Date().toISOString(),
  },

  // --- HARDWARE & ACCESSORIES ---
  {
    id: 'mat-hw-engsel-3in',
    itemCode: 'HW-ENG-3',
    name: 'Engsel Jendela / Pintu Casement Stainless (Set/Pasang)',
    category: 'hardware',
    unit: 'set',
    pricePerUnit: 35000,
    stockQuantity: 60,
    minStockThreshold: 20,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-hw-kunci-pintu',
    itemCode: 'HW-KNC-PNT',
    name: 'Kunci + Handle Pintu Alumunium Set',
    category: 'hardware',
    unit: 'set',
    pricePerUnit: 165000,
    stockQuantity: 15,
    minStockThreshold: 5,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-hw-kunci-sliding',
    itemCode: 'HW-KNC-SLD',
    name: 'Kunci Tanam Pintu/Jendela Sliding',
    category: 'hardware',
    unit: 'pcs',
    pricePerUnit: 65000,
    stockQuantity: 25,
    minStockThreshold: 10,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-hw-friction-stay',
    itemCode: 'HW-FRC-STY',
    name: 'Hak Angin Friction Stay Stainless 12-16 Inch (Pasang)',
    category: 'hardware',
    unit: 'set',
    pricePerUnit: 55000,
    stockQuantity: 4, // LOW STOCK ALERT
    minStockThreshold: 10,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-acc-sealant',
    itemCode: 'ACC-SLN-SLV',
    name: 'Sealant Silicone Alumunium (Tube)',
    category: 'accessories',
    unit: 'pcs',
    pricePerUnit: 38000,
    stockQuantity: 45,
    minStockThreshold: 15,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-acc-karet',
    itemCode: 'ACC-KRT-MTR',
    name: 'Karet Seal Kusen & Kaca (Roll / Meter)',
    category: 'accessories',
    unit: 'meter',
    pricePerUnit: 4500,
    stockQuantity: 300,
    minStockThreshold: 50,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'mat-acc-sekrup-siku',
    itemCode: 'ACC-SKR-SKU',
    name: 'Sekrup, Fischer, Siku Sudut & Rivet (Paket Per Frame)',
    category: 'accessories',
    unit: 'set',
    pricePerUnit: 15000,
    stockQuantity: 100,
    minStockThreshold: 30,
    lastUpdated: new Date().toISOString(),
  },

  // --- STANDARD LABOR RATES (UPAH TUKANG) ---
  {
    id: 'lab-rate-m1',
    itemCode: 'LAB-M1-STD',
    name: 'Upah Pasang Kusen Alumunium per Meter Lari (m1)',
    category: 'labor_rate',
    unit: 'm1',
    pricePerUnit: 35000, // Rp 35.000 / m1
    stockQuantity: 999,
    minStockThreshold: 0,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'lab-rate-hok',
    itemCode: 'LAB-HOK-STD',
    name: 'Upah Tukang Spesialis Alumunium per HOK (Hari Kerja)',
    category: 'labor_rate',
    unit: 'pcs',
    pricePerUnit: 185000, // Rp 185.000 / Hari
    stockQuantity: 999,
    minStockThreshold: 0,
    lastUpdated: new Date().toISOString(),
  }
];
